<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.p7yt7vT' shared service.

return $this->privates['.service_locator.p7yt7vT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'contact' => ['privates', '.errored..service_locator.p7yt7vT.App\\Entity\\Contact', NULL, 'Cannot autowire service ".service_locator.p7yt7vT": it references class "App\\Entity\\Contact" but no such service exists.'],
], [
    'contact' => 'App\\Entity\\Contact',
]);
