<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Z7b6Utq' shared service.

return $this->privates['.service_locator.Z7b6Utq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ContactController::delete' => ['privates', '.service_locator.p7yt7vT', 'get_ServiceLocator_P7yt7vTService.php', true],
    'App\\Controller\\ContactController::edit' => ['privates', '.service_locator.p7yt7vT', 'get_ServiceLocator_P7yt7vTService.php', true],
    'App\\Controller\\ContactController::index' => ['privates', '.service_locator.U5qUtgW', 'get_ServiceLocator_U5qUtgWService.php', true],
    'App\\Controller\\ContactController::new' => ['privates', '.service_locator.T8zT56I', 'get_ServiceLocator_T8zT56IService.php', true],
    'App\\Controller\\ContactController::show' => ['privates', '.service_locator.p7yt7vT', 'get_ServiceLocator_P7yt7vTService.php', true],
    'App\\Controller\\ContactController:delete' => ['privates', '.service_locator.p7yt7vT', 'get_ServiceLocator_P7yt7vTService.php', true],
    'App\\Controller\\ContactController:edit' => ['privates', '.service_locator.p7yt7vT', 'get_ServiceLocator_P7yt7vTService.php', true],
    'App\\Controller\\ContactController:index' => ['privates', '.service_locator.U5qUtgW', 'get_ServiceLocator_U5qUtgWService.php', true],
    'App\\Controller\\ContactController:new' => ['privates', '.service_locator.T8zT56I', 'get_ServiceLocator_T8zT56IService.php', true],
    'App\\Controller\\ContactController:show' => ['privates', '.service_locator.p7yt7vT', 'get_ServiceLocator_P7yt7vTService.php', true],
], [
    'App\\Controller\\ContactController::delete' => '?',
    'App\\Controller\\ContactController::edit' => '?',
    'App\\Controller\\ContactController::index' => '?',
    'App\\Controller\\ContactController::new' => '?',
    'App\\Controller\\ContactController::show' => '?',
    'App\\Controller\\ContactController:delete' => '?',
    'App\\Controller\\ContactController:edit' => '?',
    'App\\Controller\\ContactController:index' => '?',
    'App\\Controller\\ContactController:new' => '?',
    'App\\Controller\\ContactController:show' => '?',
]);
