<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Utils\Mailing\Contact' shared autowired service.

include_once $this->targetDirs[3].'/src/Utils/Mailing/Contact.php';

return $this->privates['App\\Utils\\Mailing\\Contact'] = new \App\Utils\Mailing\Contact(($this->services['swiftmailer.mailer.default'] ?? $this->load('getSwiftmailer_Mailer_DefaultService.php')), ($this->services['twig'] ?? $this->getTwigService()), $this->getEnv('MAILER_SENDER'), $this->getEnv('MAILER_BCC'));
