<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.T8zT56I' shared service.

return $this->privates['.service_locator.T8zT56I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'service' => ['privates', 'App\\Utils\\Mailing\\Contact', 'getContact2Service.php', true],
], [
    'service' => 'App\\Utils\\Mailing\\Contact',
]);
