<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCXXMBoL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCXXMBoL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCXXMBoL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCXXMBoL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCXXMBoL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CXXMBoL',
    'container.build_id' => '01523e02',
    'container.build_time' => 1569348546,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCXXMBoL');
