<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVcEC50H\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVcEC50H/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVcEC50H.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVcEC50H\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVcEC50H\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VcEC50H',
    'container.build_id' => 'b2ac3c9f',
    'container.build_time' => 1569346206,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVcEC50H');
