<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6x5k1sm\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6x5k1sm/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6x5k1sm.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6x5k1sm\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6x5k1sm\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6x5k1sm',
    'container.build_id' => '7f8943be',
    'container.build_time' => 1569347842,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6x5k1sm');
